# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../../../../../../Users/lukastk/dev/2025-11-09_00__repoyard/pts/mod/cmds/02_get_repo_sync_status.pct.py.

# %% top_export
from pathlib import Path
from enum import Enum

from repoyard.config import get_config, StorageType
from repoyard._models import SyncStatus
from repoyard import const

# %% top_export
from typing import NamedTuple
class RepoSyncStatus(NamedTuple):
    meta: SyncStatus
    conf: SyncStatus
    data: SyncStatus

def get_repo_sync_status(
    config_path: Path,
    repo_full_name: str,
) -> dict[str, SyncStatus]:
    """
    """
    
    # AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../../../../../../Users/lukastk/dev/2025-11-09_00__repoyard/pts/mod/cmds/02_get_repo_sync_status.pct.py.
    
    # %% auto 0
    __all__ = ['config', 'repoyard_meta', 'repo_meta', 'repo_sync_status']
    
    # %% ../../../../../../../../../Users/lukastk/dev/2025-11-09_00__repoyard/pts/mod/cmds/02_get_repo_sync_status.pct.py 13
    config = get_config(config_path)
    
    # %% ../../../../../../../../../Users/lukastk/dev/2025-11-09_00__repoyard/pts/mod/cmds/02_get_repo_sync_status.pct.py 16
    from .._models import get_repoyard_meta
    repoyard_meta = get_repoyard_meta(config)
    
    if repo_full_name not in repoyard_meta.by_full_name:
        raise ValueError(f"Repo '{repo_full_name}' not found.")
    
    repo_meta = repoyard_meta.by_full_name[repo_full_name]
    
    # %% ../../../../../../../../../Users/lukastk/dev/2025-11-09_00__repoyard/pts/mod/cmds/02_get_repo_sync_status.pct.py 17
    from .._models import get_sync_status, RepoPart
    
    repo_sync_status = RepoSyncStatus(
        meta=get_sync_status(
            rclone_config_path=config.rclone_config_path,
            local_path=repo_meta.get_local_repometa_path(config),
            local_sync_record_path=repo_meta.get_local_sync_record_path(config, RepoPart.META),
            remote=repo_meta.storage_location,
            remote_path=repo_meta.get_remote_repometa_path(config),
            remote_sync_record_path=repo_meta.get_remote_sync_record_path(config, RepoPart.META),
        ),
    
        conf=get_sync_status(
            rclone_config_path=config.rclone_config_path,
            local_path=repo_meta.get_local_repoconf_path(config),
            local_sync_record_path=repo_meta.get_local_sync_record_path(config, RepoPart.CONF),
            remote=repo_meta.storage_location,
            remote_path=repo_meta.get_remote_repoconf_path(config),
            remote_sync_record_path=repo_meta.get_remote_sync_record_path(config, RepoPart.CONF),
        ),
    
        data=get_sync_status(
            rclone_config_path=config.rclone_config_path,
            local_path=repo_meta.get_local_repodata_path(config),
            local_sync_record_path=repo_meta.get_local_sync_record_path(config, RepoPart.DATA),
            remote=repo_meta.storage_location,
            remote_path=repo_meta.get_remote_repodata_path(config),
            remote_sync_record_path=repo_meta.get_remote_sync_record_path(config, RepoPart.DATA),
        ),
    )
    return repo_sync_status;