# AUTOGENERATED! DO NOT EDIT! File to edit: pts/tests/unit/config/test_storage_config.pct.py

__all__ = ['TestStorageConfigConstruction', 'TestStorageConfigPathExpansion', 'TestStorageConfigPathFormats', 'TestStorageConfigRequiredFields', 'TestStorageConfigStrictMode', 'TestStorageType']

# %% pts/tests/unit/config/test_storage_config.pct.py 2
import pytest
from pathlib import Path
from pydantic import ValidationError

from boxyard.config import StorageConfig, StorageType


# ============================================================================
# Tests for StorageType enum
# ============================================================================

# %% pts/tests/unit/config/test_storage_config.pct.py 3
class TestStorageType:
    """Tests for the StorageType enum."""

    def test_storage_type_values(self):
        """StorageType has correct values."""
        assert StorageType.RCLONE.value == "rclone"
        assert StorageType.LOCAL.value == "local"

    def test_storage_type_count(self):
        """There are exactly 2 storage types."""
        assert len(StorageType) == 2


# ============================================================================
# Tests for StorageConfig construction
# ============================================================================

# %% pts/tests/unit/config/test_storage_config.pct.py 4
class TestStorageConfigConstruction:
    """Tests for StorageConfig construction."""

    def test_rclone_storage_type(self):
        """rclone storage type can be configured."""
        config = StorageConfig(
            storage_type="rclone",
            store_path="remote:bucket/path",
        )

        assert config.storage_type == StorageType.RCLONE
        assert config.store_path == Path("remote:bucket/path")

    def test_local_storage_type(self):
        """local storage type can be configured."""
        config = StorageConfig(
            storage_type="local",
            store_path="/home/user/storage",
        )

        assert config.storage_type == StorageType.LOCAL
        assert config.store_path == Path("/home/user/storage")

    def test_storage_type_from_enum(self):
        """StorageType enum can be passed directly."""
        config = StorageConfig(
            storage_type=StorageType.LOCAL,
            store_path="/tmp/storage",
        )

        assert config.storage_type == StorageType.LOCAL

    def test_invalid_storage_type(self):
        """Invalid storage type raises error."""
        with pytest.raises(ValidationError):
            StorageConfig(
                storage_type="invalid",
                store_path="/tmp/storage",
            )


# ============================================================================
# Tests for path expansion
# ============================================================================

# %% pts/tests/unit/config/test_storage_config.pct.py 5
class TestStorageConfigPathExpansion:
    """Tests for path expansion in StorageConfig."""

    def test_tilde_expansion(self):
        """Tilde is expanded in store_path."""
        config = StorageConfig(
            storage_type="local",
            store_path="~/storage",
        )

        assert "~" not in str(config.store_path)
        assert config.store_path.is_absolute()

    def test_absolute_path_unchanged(self):
        """Absolute paths are preserved."""
        config = StorageConfig(
            storage_type="local",
            store_path="/absolute/path/to/storage",
        )

        assert str(config.store_path) == "/absolute/path/to/storage"

    def test_relative_path_kept(self):
        """Relative paths (without tilde) are kept as-is."""
        config = StorageConfig(
            storage_type="local",
            store_path="relative/path",
        )

        assert str(config.store_path) == "relative/path"

    def test_rclone_remote_path(self):
        """rclone remote paths are preserved."""
        config = StorageConfig(
            storage_type="rclone",
            store_path="myremote:bucket/boxyard",
        )

        assert str(config.store_path) == "myremote:bucket/boxyard"


# ============================================================================
# Tests for required fields
# ============================================================================

# %% pts/tests/unit/config/test_storage_config.pct.py 6
class TestStorageConfigRequiredFields:
    """Tests for required fields in StorageConfig."""

    def test_missing_storage_type(self):
        """Missing storage_type raises error."""
        with pytest.raises(ValidationError):
            StorageConfig(
                store_path="/tmp/storage",
            )

    def test_missing_store_path(self):
        """Missing store_path raises error."""
        with pytest.raises(ValidationError):
            StorageConfig(
                storage_type="local",
            )


# ============================================================================
# Tests for strict mode
# ============================================================================

# %% pts/tests/unit/config/test_storage_config.pct.py 7
class TestStorageConfigStrictMode:
    """Tests for strict mode in StorageConfig."""

    def test_extra_field_raises_error(self):
        """Extra fields raise error due to strict mode."""
        with pytest.raises(ValidationError, match="extra"):
            StorageConfig(
                storage_type="local",
                store_path="/tmp/storage",
                unknown_field="value",
            )


# ============================================================================
# Tests for various path formats
# ============================================================================

# %% pts/tests/unit/config/test_storage_config.pct.py 8
class TestStorageConfigPathFormats:
    """Tests for various path formats in StorageConfig."""

    def test_windows_style_path(self):
        """Windows-style paths are handled."""
        # Note: On Unix, this is just a regular path with backslashes
        config = StorageConfig(
            storage_type="local",
            store_path="C:/Users/test/storage",
        )

        assert config.store_path is not None

    def test_path_with_spaces(self):
        """Paths with spaces are handled."""
        config = StorageConfig(
            storage_type="local",
            store_path="/path/with spaces/storage",
        )

        assert " " in str(config.store_path)

    def test_path_with_special_chars(self):
        """Paths with special characters are handled."""
        config = StorageConfig(
            storage_type="local",
            store_path="/path-with_special.chars/storage",
        )

        assert config.store_path is not None

    def test_s3_style_path(self):
        """S3-style rclone paths are handled."""
        config = StorageConfig(
            storage_type="rclone",
            store_path="s3:my-bucket/boxyard/data",
        )

        assert str(config.store_path) == "s3:my-bucket/boxyard/data"

    def test_sftp_style_path(self):
        """SFTP-style rclone paths are handled."""
        config = StorageConfig(
            storage_type="rclone",
            store_path="sftp:server:/home/user/backup",
        )

        assert "sftp:" in str(config.store_path)

    def test_google_drive_path(self):
        """Google Drive rclone paths are handled."""
        config = StorageConfig(
            storage_type="rclone",
            store_path="gdrive:MyDrive/Backups/boxyard",
        )

        assert "gdrive:" in str(config.store_path)
