# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path

from .._models import RepoPart, SyncStatus
from ..config import get_config


async def get_repo_sync_status(
    config_path: Path,
    repo_index_name: str,
) -> dict[RepoPart, SyncStatus]:
    """ """
    config = get_config(config_path)
    from repoyard._models import get_repoyard_meta

    repoyard_meta = get_repoyard_meta(config)

    if repo_index_name not in repoyard_meta.by_index_name:
        raise ValueError(f"Repo '{repo_index_name}' not found.")

    repo_meta = repoyard_meta.by_index_name[repo_index_name]
    import asyncio

    from repoyard._models import RepoPart, get_sync_status

    tasks = [
        get_sync_status(
            rclone_config_path=config.rclone_config_path,
            local_path=repo_meta.get_local_part_path(config, RepoPart.META),
            local_sync_record_path=repo_meta.get_local_sync_record_path(config, repo_part),
            remote=repo_meta.storage_location,
            remote_path=repo_meta.get_remote_part_path(config, RepoPart.META),
            remote_sync_record_path=repo_meta.get_remote_sync_record_path(config, repo_part),
        )
        for repo_part in RepoPart
    ]

    repo_sync_status = {
        repo_part: sync_status for repo_part, sync_status in zip(RepoPart, await asyncio.gather(*tasks))
    }
    return repo_sync_status
