# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path
import asyncio

from .._utils.sync_helper import SyncSetting
from ..config import get_config
from .._utils.locking import BoxyardLockManager, LockAcquisitionError, BOX_SYNC_LOCK_TIMEOUT, acquire_lock_async


async def exclude_box(
    config_path: Path,
    box_index_name: str,
    skip_sync: bool = False,
    soft_interruption_enabled: bool = True,
):
    """ """
    config = get_config(config_path)
    from boxyard._models import get_boxyard_meta

    boxyard_meta = get_boxyard_meta(config)

    if box_index_name not in boxyard_meta.by_index_name:
        raise ValueError(f"Box '{box_index_name}' does not exist.")

    box_meta = boxyard_meta.by_index_name[box_index_name]

    if not box_meta.check_included(config):
        raise ValueError(f"Box '{box_index_name}' is already excluded.")
    from boxyard.config import StorageType

    if box_meta.get_storage_location_config(config).storage_type == StorageType.LOCAL:
        raise ValueError(
            f"Box '{box_index_name}' in local storage location '{box_meta.storage_location}' cannot be excluded."
        )
    import shutil
    from boxyard._models import BoxPart
    from boxyard.cmds import sync_box

    _lock_manager = BoxyardLockManager(config.boxyard_data_path)
    _lock_path = _lock_manager.box_sync_lock_path(box_index_name)
    _lock_manager._ensure_lock_dir(_lock_path)
    _sync_lock = __import__("filelock").FileLock(_lock_path, timeout=0)
    await acquire_lock_async(
        _sync_lock,
        f"box sync ({box_index_name})",
        _lock_path,
        BOX_SYNC_LOCK_TIMEOUT,
    )
    try:
        # Sync any changes before removing locally
        if not skip_sync:
            await sync_box(
                config_path=config_path,
                box_index_name=box_index_name,
                sync_setting=SyncSetting.CAREFUL,
                soft_interruption_enabled=soft_interruption_enabled,
                _skip_lock=True,
            )

        # Exclude it - delete local data
        shutil.rmtree(box_meta.get_local_part_path(config, BoxPart.DATA))
        box_meta.get_local_sync_record_path(config, BoxPart.DATA).unlink()
    finally:
        _sync_lock.release()
