# AUTOGENERATED! DO NOT EDIT! File to edit: pts/mod/_tombstones.pct.py

__all__ = ['Tombstone', 'create_tombstone', 'get_tombstone', 'get_tombstone_path', 'is_tombstoned', 'list_tombstones', 'remove_tombstone']

# %% pts/mod/_tombstones.pct.py 3
from datetime import UTC, datetime

import repoyard.config

from . import const


# %% pts/mod/_tombstones.pct.py 5
class Tombstone(const.StrictModel):
    """
    A tombstone marks a deleted repository.

    Stored at: {storage_location}:{store_path}/tombstones/{repo_id}.json
    """
    repo_id: str
    deleted_at_utc: datetime
    deleted_by_hostname: str
    last_known_name: str

# %% pts/mod/_tombstones.pct.py 7
def get_tombstone_path(repo_id: str) -> str:
    """Get the relative path for a tombstone file."""
    return f"tombstones/{repo_id}.json"

# %% pts/mod/_tombstones.pct.py 8
async def create_tombstone(
    config: repoyard.config.Config,
    storage_location: str,
    repo_id: str,
    last_known_name: str,
) -> Tombstone:
    """
    Create a tombstone for a deleted repo on the remote storage.

    Args:
        config: Repoyard config
        storage_location: Name of the storage location
        repo_id: The repo ID being deleted
        last_known_name: The last known name of the repo

    Returns:
        The created Tombstone
    """
    from ._utils import get_hostname
    from ._utils.rclone import rclone_write

    tombstone = Tombstone(
        repo_id=repo_id,
        deleted_at_utc=datetime.now(UTC),
        deleted_by_hostname=get_hostname(),
        last_known_name=last_known_name,
    )

    sl_config = config.storage_locations[storage_location]
    tombstone_path = sl_config.store_path / get_tombstone_path(repo_id)

    await rclone_write(
        rclone_config_path=config.rclone_config_path,
        dest=storage_location,
        dest_path=tombstone_path.as_posix(),
        content=tombstone.model_dump_json(indent=2),
    )

    return tombstone

# %% pts/mod/_tombstones.pct.py 9
async def is_tombstoned(
    config: repoyard.config.Config,
    storage_location: str,
    repo_id: str,
) -> bool:
    """
    Check if a repo_id has been tombstoned.

    Args:
        config: Repoyard config
        storage_location: Name of the storage location
        repo_id: The repo ID to check

    Returns:
        True if the repo has been tombstoned, False otherwise
    """
    from ._utils.rclone import rclone_path_exists

    sl_config = config.storage_locations[storage_location]
    tombstone_path = sl_config.store_path / get_tombstone_path(repo_id)

    exists, _ = await rclone_path_exists(
        rclone_config_path=config.rclone_config_path,
        source=storage_location,
        source_path=tombstone_path.as_posix(),
    )
    return exists

# %% pts/mod/_tombstones.pct.py 10
async def get_tombstone(
    config: repoyard.config.Config,
    storage_location: str,
    repo_id: str,
) -> Tombstone | None:
    """
    Get tombstone info for a repo_id.

    Args:
        config: Repoyard config
        storage_location: Name of the storage location
        repo_id: The repo ID to look up

    Returns:
        Tombstone if found, None otherwise
    """
    from ._utils.rclone import rclone_cat

    sl_config = config.storage_locations[storage_location]
    tombstone_path = sl_config.store_path / get_tombstone_path(repo_id)

    exists, content = await rclone_cat(
        rclone_config_path=config.rclone_config_path,
        source=storage_location,
        source_path=tombstone_path.as_posix(),
    )

    if not exists or content is None:
        return None

    return Tombstone.model_validate_json(content)

# %% pts/mod/_tombstones.pct.py 11
async def list_tombstones(
    config: repoyard.config.Config,
    storage_location: str,
) -> list[Tombstone]:
    """
    List all tombstones for a storage location.

    Args:
        config: Repoyard config
        storage_location: Name of the storage location

    Returns:
        List of Tombstone objects
    """
    from ._utils.rclone import rclone_cat, rclone_lsjson

    sl_config = config.storage_locations[storage_location]
    tombstones_dir = sl_config.store_path / "tombstones"

    files = await rclone_lsjson(
        rclone_config_path=config.rclone_config_path,
        source=storage_location,
        source_path=tombstones_dir.as_posix(),
    )

    if files is None:
        return []

    tombstones = []
    for f in files:
        if f.get("Name", "").endswith(".json") and not f.get("IsDir", False):
            file_path = tombstones_dir / f["Name"]
            exists, content = await rclone_cat(
                rclone_config_path=config.rclone_config_path,
                source=storage_location,
                source_path=file_path.as_posix(),
            )
            if exists and content:
                tombstones.append(Tombstone.model_validate_json(content))

    return tombstones

# %% pts/mod/_tombstones.pct.py 12
async def remove_tombstone(
    config: repoyard.config.Config,
    storage_location: str,
    repo_id: str,
) -> None:
    """
    Remove a tombstone, allowing a repo ID to be reused.

    Use for recovering from accidental deletions.

    Args:
        config: Repoyard config
        storage_location: Name of the storage location
        repo_id: The repo ID to untombstone

    Raises:
        ValueError: If no tombstone exists for the repo ID
    """
    from ._utils.rclone import rclone_delete, rclone_path_exists

    sl_config = config.storage_locations[storage_location]
    tombstone_path = sl_config.store_path / get_tombstone_path(repo_id)

    exists, _ = await rclone_path_exists(
        rclone_config_path=config.rclone_config_path,
        source=storage_location,
        source_path=tombstone_path.as_posix(),
    )

    if not exists:
        raise ValueError(f"No tombstone found for repo ID '{repo_id}'")

    await rclone_delete(
        rclone_config_path=config.rclone_config_path,
        dest=storage_location,
        dest_path=tombstone_path.as_posix(),
    )
