# AUTOGENERATED! DO NOT EDIT!

import asyncio

import pytest

from repoyard._models import RepoPart, get_repoyard_meta
from repoyard._utils.sync_helper import SyncUnsafe
from repoyard.cmds import (
    include_repo,
    new_repo,
    sync_missing_repometas,
    sync_repo,
)

from ...integration.conftest import create_repoyards


@pytest.mark.integration
def test_multi_machine_sync():
    """Test syncing between multiple machines with conflict detection."""
    asyncio.run(_test_multi_machine_sync())


async def _test_multi_machine_sync():
    num_repos = 5
    (
        sl_name,
        sl_rclone_path,
        [(config1, config_path1, data_path1), (config2, config_path2, data_path2)],
    ) = create_repoyards(num_repoyards=2)
    repo_index_names = []

    async def _task(i):
        repo_index_name = new_repo(config_path=config_path1, repo_name=f"test_repo_{i}", storage_location=sl_name)
        await sync_repo(config_path=config_path1, repo_index_name=repo_index_name)
        repo_index_names.append(repo_index_name)

    await asyncio.gather(*[_task(i) for i in range(num_repos)])
    await sync_missing_repometas(config_path=config_path2)

    repoyard_meta2 = get_repoyard_meta(config2)
    assert len(repoyard_meta2.repo_metas) == num_repos

    async def _task(repo_meta):
        await include_repo(
            config_path=config_path2,
            repo_index_name=repo_meta.index_name,
        )

    await asyncio.gather(*[_task(repo_meta) for repo_meta in repoyard_meta2.repo_metas])

    async def _task(repo_meta):
        (repo_meta.get_local_part_path(config2, RepoPart.DATA) / "hello.txt").write_text("Hello, world!")
        await sync_repo(
            config_path=config_path2,
            repo_index_name=repo_meta.index_name,
        )

    await asyncio.gather(*[_task(repo_meta) for repo_meta in repoyard_meta2.repo_metas])
    repoyard_meta1 = get_repoyard_meta(config1)

    await asyncio.gather(
        *[
            sync_repo(
                config_path=config_path1,
                repo_index_name=repo_meta.index_name,
            )
            for repo_meta in repoyard_meta1.repo_metas
        ]
    )

    async def _task(repo_meta):
        # Create a change on machine 1 and sync
        (repo_meta.get_local_part_path(config1, RepoPart.DATA) / "goodbye.txt").write_text("Goodbye, world!")
        await sync_repo(
            config_path=config_path1,
            repo_index_name=repo_meta.index_name,
        )

        # Try to create a conflicting change on machine 2 and sync - should raise
        with pytest.raises(SyncUnsafe):
            (repo_meta.get_local_part_path(config2, RepoPart.DATA) / "goodbye.txt").write_text("I'm sorry, world!")
            await sync_repo(
                config_path=config_path2,
                repo_index_name=repo_meta.index_name,
            )

    await asyncio.gather(*[_task(repo_meta) for repo_meta in repoyard_meta1.repo_metas])
