# AUTOGENERATED! DO NOT EDIT!

import asyncio
from pathlib import Path

import pytest

from repoyard._models import RepoPart, get_repoyard_meta
from repoyard.cmds import delete_repo, new_repo
from repoyard.config import get_config

from ...integration.conftest import create_repoyards


@pytest.mark.integration
def test_new_repo():
    """Test creating new repositories with various options."""
    asyncio.run(_test_new_repo())


async def _test_new_repo():
    remote_name, remote_rclone_path, config, config_path, data_path = create_repoyards()
    repo1 = new_repo(
        config_path=config_path,
        repo_name="basic-repo",
        storage_location=remote_name,
    )

    config = get_config(config_path)
    repoyard_meta = get_repoyard_meta(config, force_create=True)
    repo_meta1 = repoyard_meta.by_index_name[repo1]

    # Verify repo was created
    assert repo_meta1.name == "basic-repo"
    assert repo_meta1.storage_location == remote_name
    assert repo_meta1.check_included(config)

    # Verify local paths exist
    assert repo_meta1.get_local_path(config).exists()
    assert repo_meta1.get_local_part_path(config, RepoPart.DATA).exists()
    import tempfile

    # Create a temp directory with some content
    source_dir = Path(tempfile.mkdtemp())
    (source_dir / "existing_file.txt").write_text("Existing content")
    (source_dir / "subdir").mkdir()
    (source_dir / "subdir" / "nested.txt").write_text("Nested content")

    # Create repo from this directory (move mode)
    repo3 = new_repo(
        config_path=config_path,
        repo_name="from-existing",
        storage_location=remote_name,
        from_path=source_dir,
        copy_from_path=False,  # Move, not copy
    )

    config = get_config(config_path)
    repoyard_meta = get_repoyard_meta(config, force_create=True)
    repo_meta3 = repoyard_meta.by_index_name[repo3]

    # Verify content was moved
    data_path = repo_meta3.get_local_part_path(config, RepoPart.DATA)
    assert (data_path / "existing_file.txt").exists()
    assert (data_path / "existing_file.txt").read_text() == "Existing content"
    assert (data_path / "subdir" / "nested.txt").exists()

    # Source should be moved (not exist)
    # Note: The move behavior depends on implementation
    # assert not source_dir.exists()  # May or may not be true
    from repoyard.cmds import modify_repometa

    repo4 = new_repo(
        config_path=config_path,
        repo_name="grouped-repo",
        storage_location=remote_name,
    )

    # Add groups via modify_repometa
    modify_repometa(
        config_path=config_path,
        repo_index_name=repo4,
        modifications={"groups": ["backend", "python", "api"]},
    )

    config = get_config(config_path)
    repoyard_meta = get_repoyard_meta(config, force_create=True)
    repo_meta4 = repoyard_meta.by_index_name[repo4]

    # Verify groups were set
    assert "backend" in repo_meta4.groups
    assert "python" in repo_meta4.groups
    assert "api" in repo_meta4.groups
    for repo in [repo1, repo3, repo4]:
        await delete_repo(config_path=config_path, repo_index_name=repo)
