# AUTOGENERATED! DO NOT EDIT!

from pathlib import Path
import subprocess
import os
from typing import Literal, Any

from .._utils import get_repo_index_name_from_sub_path
from ..config import get_config, StorageType
from .. import const

class RepoNameConflict(Exception): pass

def modify_repometa(
    config_path: Path,
    repo_index_name: str,
    modifications: dict[str, Any] = {},
):
    """
    """
    config = get_config(config_path)
    from repoyard._models import get_repoyard_meta, RepoMeta
    repoyard_meta = get_repoyard_meta(config)
    
    if repo_index_name not in repoyard_meta.by_index_name:
        raise ValueError(f"Repo '{repo_index_name}' not found.")
    
    repo_meta = repoyard_meta.by_index_name[repo_index_name]
    modified_repo_meta = RepoMeta(**{
        **repo_meta.model_dump(),
        **modifications
    })
    #TESTREF: test_modify_repometa_unique_names
    from repoyard._models import get_repo_group_configs
    
    # Construct modified repo_metas list
    _old_repo_meta = repoyard_meta.by_index_name[repo_index_name]
    _repo_metas = list(repoyard_meta.repo_metas)
    _repo_metas.remove(_old_repo_meta)
    _repo_metas.append(modified_repo_meta)
    
    repo_group_configs, virtual_repo_groups = get_repo_group_configs(config, _repo_metas)
    for g in modified_repo_meta.groups:
        if g in virtual_repo_groups:
            raise Exception(f"Cannot add a repository to a virtual repo group (virtual repo group: '{g}')")
    
        repo_group_config = repo_group_configs[g]
        repo_metas_in_group = [rm for rm in _repo_metas if g in rm.groups]
    
        if repo_group_config.unique_repo_names:
            name_counts = {repo_meta.name: 0 for repo_meta in repo_metas_in_group}
            for repo_meta in repo_metas_in_group:
                name_counts[repo_meta.name] += 1
            duplicate_names = [(name, count) for name, count in name_counts.items() if count > 1]
            if duplicate_names:
                names_str = ", ".join(f"'{name}' (count: {count})" for name, count in duplicate_names)
                raise RepoNameConflict(f"Error modifying repo meta for '{repo_index_name}':\n"
                                 f"Repo is in group '{g}' which requires unique names. After the modification, the following name(s) appear multiple times in this group: {names_str}.")
    modified_repo_meta.save(config)
    from repoyard._models import refresh_repoyard_meta
    refresh_repoyard_meta(config)
